version: "3.9"
services:
  comdb2-node1:
    container_name: node1
    hostname: node1
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    privileged: true
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node1-dbs:/home/heisengarg/dbs
      - ./volumes/node1-ssh:/home/heisengarg/.ssh
    networks:
      - cluster-net
      - client-net
        #    restart: unless-stopped
    cap_add:
      - ALL
  comdb2-node2:
    container_name: node2
    hostname: node2
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    privileged: true
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node2-dbs:/home/heisengarg/dbs
      - ./volumes/node2-ssh:/home/heisengarg/.ssh
    networks:
      - cluster-net
      - client-net
        # restart: unless-stopped
    cap_add:
      - ALL
  comdb2-node3:
    container_name: node3
    hostname: node3
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    privileged: true
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node3-dbs:/home/heisengarg/dbs
      - ./volumes/node3-ssh:/home/heisengarg/.ssh
    networks:
      - cluster-net
      - client-net
        # restart: unless-stopped
    cap_add:
      - ALL
  comdb2-node4:
    container_name: node4
    hostname: node4
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    privileged: true
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node4-dbs:/home/heisengarg/dbs
      - ./volumes/node4-ssh:/home/heisengarg/.ssh
    networks:
      - cluster-net
      - client-net
        # restart: unless-stopped
    cap_add:
      - ALL
  comdb2-node5:
    container_name: node5
    hostname: node5
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    privileged: true
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node5-dbs:/home/heisengarg/dbs
      - ./volumes/node5-ssh:/home/heisengarg/.ssh
    networks:
      - cluster-net
      - client-net
        # restart: unless-stopped
    cap_add:
      - ALL
  comdb2-client:
    container_name: client
    hostname: client
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg/src
    privileged: true
    command: ["diskeys", "node1,node2,node3,node4,node5"]
    environment:
     - CLUSTER="node1 node2 node3,node4,node5"
    volumes:
      - comdb2-src:/home/heisengarg/src
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/client-ssh:/home/heisengarg/.ssh
    networks:
      - client-net
    cap_add:
      - ALL

volumes:
  comdb2-src:
    external: true

networks:
  cluster-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64
  client-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 173.16.239.0/24
      - subnet: 2001:3984:3990::/64
