version: "3.9"
services:
  comdb2-node1:
    container_name: node1
    hostname: node1 
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node1-dbs:/home/heisengarg/dbs
    networks:
      - cluster-net
      - client-net
    restart: unless-stopped
    cap_add:
      - ALL
  comdb2-node2:
    container_name: node2
    hostname: node2
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node2-dbs:/home/heisengarg/dbs
    networks:
      - cluster-net
      - client-net
    restart: unless-stopped
    cap_add:
      - ALL
  comdb2-node3:
    container_name: node3
    hostname: node3
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg
    command: ["run", "mogargdb"]
    volumes:
      - ./volumes/bin:/opt/bb/bin
      - ./volumes/node3-dbs:/home/heisengarg/dbs
    networks:
      - cluster-net
      - client-net
    restart: unless-stopped
    cap_add:
      - ALL
  comdb2-client:
    container_name: client
    hostname: client
    image: heisengarg/comdb2-dev:latest
    working_dir: /home/heisengarg/src
    command: ["diskeys", "node1,node2,node3"]
    environment:
     - CLUSTER="node1 node2 node3"
    volumes:
      - comdb2-src:/home/heisengarg/src
      - ./volumes/bin:/opt/bb/bin
    networks:
      - client-net
    cap_add:
      - ALL

volumes:
  comdb2-src:
    external: true

networks:
  cluster-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64
  client-net:
    driver: bridge 
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
      - subnet: 2001:3984:3990::/64
